outpout_dir: models/
prediction_dir: training_prediction/
# model_architecture: caformer_s18.sail_in1k
model_architecture : caformer_s18.sail_in1k
pretrained: True
image_net_normalize : False
channel : 3
loss: "BCE"
number_kfold: 5
regularization: False
lambda_l1: 0.1
data_augmentation: True
gpu_device: 0
lr: 1e-4
batch_size: 4
epochs: 40
workers: 8 
seed: 123
log_dir : log/
tbp: 8888
auto_eval: True