outpout_dir: models/
prediction_dir: training_prediction/
model_architecture: davit_base.msft_in1k
pretrained: True
preprocessing: "PCA"
image_net_normalize : False
resize: [512, 512]
channel : 3
loss: BCE
number_kfold: 5
data_augmentation: False
gpu_device: 0
lr: 1e-4
batch_size: 4
epochs: 10
workers: 8 
seed: 123
tbp: 8888
auto_eval: True